Update README and add quickstart
substratusai/substratus pull request #113
Opened 2023-07-20 05:57 UTC by samos123

2023-07-20 17:39 UTC, brandonjbjelland commented
+1 to keeping the landing README small and linking to child docs and our landing site as much as possible.

It's reasonable to imaging the repo as a user's first exposure to substratus so there should definitely be a blurb of **what** exactly substratus but I'd rather keep more thorough user docs on the doc site and dev docs here in `/docs/`. I think we should direct users via links to those two paths. Something like:

```
[substratus-logo.png]

Your cross-cloud AI substrate.

Substratus extends the Kubernetes control plane to orchestrate the
building, training, and deployment of machine learning models.
---
Interested in trying substratus? Check out the walkthrough [here](substratus.ai/link/to/docs/site).
Rolling up your sleeves to extend substratus? Dive in [here](docs/development.md).
```

2023-07-20 17:53 UTC, samos123 commented
Agreed. Let me take another pass at this and just link to the various docs from the README. 

This was purely me seeing the README and it looking too empty to me.

2023-07-20 18:40 UTC, brandonjbjelland commented
> Agreed. Let me take another pass at this and just link to the various docs from the README.
> 
> This was purely me seeing the README and it looking too empty to me.

Completely understandable! I had the same thought a bunch of times but mostly because the majority of readmes fall into one of two categories:

1. they give a ton of detail but also fail to explain what the project is at a high-level and why it exists. Instead these readmes are exhaustive and overly technical for a first-time visiting audience (e.g. here's how to build and compile the project from source and on every architecture). 95% of these readmes are out of date and don't work.
2. there's no effort given and the readme doesn't point you in the right direction. I don't know why the project exists or where to go first to figure it out.

I think we should find the right middleground between these on this readme.

1. what is substratus at a high-level and at a more technical level? Everyone should see this and have a basic understanding of what we're up to and if this is the project they'll find useful or interesting.
2. As a passerby (90%), user (9%), or potential contributor (1%), where should I go next to learn more?

2023-07-21 19:34 UTC, brandonjbjelland requested changes
https://github.com/substratusai/substratus/pull/113#issuecomment-1644416136

2023-07-21 23:10 UTC, brandonjbjelland commented on README.md
> +
```suggestion

See the [development](docs/development.md) doc to get started.

```

2023-07-21 23:11 UTC, brandonjbjelland commented on README.md
> +Substratus is still under active development and might introduce backward incompatible changes.
```suggestion
## Disclaimer

Substratus is under active development and might introduce backward incompatible changes.
```

2023-07-21 23:14 UTC, brandonjbjelland commented on README.md
> +To learn more about how Substratus works, check out the [Architecture](https://www.substratus.ai/docs/architecture) page.
```suggestion
## Intro and demo

Read the [Introduction](https://www.substratus.ai/docs/introduction) and
watch the video below:
[![Watch the video](https://img.youtube.com/vi/CLyXKJHIQ6A/hq2.jpg)](https://youtu.be/CLyXKJHIQ6A)

## Docs

Read the full docs at [substratus.ai/docs](https://www.substratus.ai/docs)

## Quickstart

Read the [Quickstart Docs](https://www.substratus.ai/docs/quickstart)

## Architecture

To learn more about how Substratus works, check out the [Architecture](https://www.substratus.ai/docs/architecture) page.
```

2023-07-21 23:15 UTC, brandonjbjelland commented on README.md
> +* Deploy large models in minutes  (e.g. latest Large Language Models)
```suggestion
Deploy and fine-tune Large Language Models on K8s in a breeze.

Features:

* Deploy large models in minutes  (e.g. latest Large Language Models)
```

2023-07-21 23:17 UTC, brandonjbjelland approved these changes
Let's do it!

2023-07-21 23:18 UTC, merged

2023-07-22 01:47 UTC, samos123 commented
Thanks for applying the suggestions directly and merging!

2023-07-22 03:45 UTC, brandonjbjelland commented
Np, this is exactly along the lines I hoped to see